### ISSUE TITLE
Error When Sending Email to Group Query

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/brifony#15]
![screen shot 2016-02-05 at 1 23 10 pm](https://cloud.githubusercontent.com/assets/13404688/12856753/0e3ff494-cc0c-11e5-99a2-dcac47f09354.png)

**Comment by IshaDakota** [comment]
fixed

**Comment by Shorashim** [comment]
Just tried to send and the error occurred again.

**Comment by IshaDakota** [comment]
it won't when I restart the server tonight.

**Comment by Shorashim** [comment]
Still isn't working for all waitlisted. Any ideas what to do?

**Comment by IshaDakota** [comment]
isn't working? or is displaying the Notice? The warning is fine. I still have error reporting on to try to solve the upload issue. This should work still with those notices.

**Comment by Shorashim** [comment]
The preview just doesn't show up. Everything disappears when I get to that step.

**Comment by IshaDakota** [comment]
which query are you coming from? The ones I'm trying are working.

**Comment by Shorashim** [comment]
Eligible & Complete and All Waitlisted. It still is showing up like the initial screenshot when I try to email the list. Any ideas on how to fix it? Thanks so much for your help!

**Comment by IshaDakota** [comment]
I may need to jump on a call with you because that's not happening with me.  What about Zach?

**Comment by Shorashim** [comment]
Happy to jump on a call. Call whenever works for you! 

Thanks!

**Comment by IshaDakota** [comment]
can you confirm that it doesn't work for Zach either.

**Comment by zpellish** [comment]
I have the same issue on mine as Lauren, however this isn't an issue when
assigning people.

On Tue, Feb 9, 2016 at 9:45 AM, Adam Stewart <notifications@github.com>
wrote:

> can you confirm that it doesn't work for Zach either.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarchingLizard/brifony/issues/15#issuecomment-181920671>
> .
>



-- 
Zach Pellish
North American Operations Manager
Shorashim
Main line: 312-267-0677
Direct line: 312-380-6536

*APPLY NOW <http://bit.ly/1USYrzo> for **Birthright Israel *
*with Shorashim this summer!*

**Comment by Shorashim** [comment]
Just wanted to check in on this as we still have not been able to send out an email planned for 10 days ago. Is this something that can be fixed or should I mail merge this email? Thanks!

**Comment by IshaDakota** [comment]
this should work now.

**Comment by IshaDakota** [comment]
@Shorashim @zpellish by the way... there sometimes seems to be a small glitch that when you click the box it doesn't populate all the boxes on the first click. We'll see if we can eliminate that, but just make sure all the boxes are checked before you move on to the next page.

**Comment by Shorashim** [comment]
All set. Thank you!!
